// <auto-generated />
namespace _3_ASP.NET_Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db));
        
        string IMigrationMetadata.Id
        {
            get { return "201707300859270_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
